name: Merge upstream branches

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge upstream
        run: |
          git config --global user.name 'RockGrub'
          git config --global user.email 'rockgrub@disroot.org'
          git config --global merge.ours.driver true

          git pull --unshallow
                               
          git remote add upstream https://github.com/terrapkg/packages
          git fetch upstream frawhide

          git checkout main
          git merge --no-edit upstream/frawhide
          git push origin main
          
          git checkout --track origin/frawhide
          git merge --no-edit upstream/frawhide
          git push origin frawhide

          git fetch upstream f42

          git checkout --track origin/f42
          git merge --no-edit upstream/f42
          git push origin f42

          git fetch upstream f41

          git checkout --track origin/f41
          git merge --no-edit upstream/f41
          git push origin f41

          git fetch upstream f40

          git checkout --track origin/f40
          git merge --no-edit upstream/f40
          git push origin f40

          git fetch upstream el10

          git checkout --track origin/el10
          git merge --no-edit upstream/el10
          git push origin el10
