name: Merge upstream branches
permissions:
  contents: write

on:
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:

jobs:
  merge:
      name: Merge upstream branches
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v4
            with:
              github_token: ${{ secrets.WORKFLOW_TOKEN }}

          - name: Set up upstream
            run: |
              git config --global user.name 'GildedRoach'
              git config --global user.email 'rockgrub@disroot.org'
              git config --global merge.ours.driver true

              git pull --unshallow
                               
              git remote add upstream https://github.com/terrapkg/packages
      
          - name: Merge main
            run: |
              git fetch upstream frawhide

              git switch -c origin/main
              git merge --no-edit upstream/frawhide
              git push origin main

          - name: Merge frawhide
            run: |
              git fetch upstream frawhide

              git checkout --track origin/frawhide
              git merge --no-edit upstream/frawhide
              git push origin frawhide

          - name: Merge f42
            run: |
              git fetch upstream f42

              git checkout --track origin/f42
              git merge --no-edit upstream/f42
              git push origin f42

          - name: Merge f41
            run: |
              git fetch upstream f41

              git checkout --track origin/f41
              git merge --no-edit upstream/f41
              git push origin f41

          - name: Merge el10
            run: |
              git fetch upstream el10

              git checkout --track origin/el10
              git merge --no-edit upstream/el10
              git push origin el10
